# Generated by Django 4.1.7 on 2023-03-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='image',
            new_name='image_field',
        ),
    ]
